# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Tests project
    - name: Test project
      run: yarn test

    # Builds project
    - name: Build project
      run: yarn build

    # Deploys to Heroku
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.2
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        # An optional buildpack to use when creating the heroku application
        buildpack: # optional
        # The branch that you would like to deploy to Heroku
        branch: # optional, default is HEAD
        # Set this to true if you don't want to use --force when switching branches
        dontuseforce: # optional
        # Will deploy using Dockerfile in project root.
        usedocker: # optional
        # Set if your app is located in a subdirectory.
        appdir: # optional, default is   
